### ISSUE TITLE
error when call .request to payone_connect

### ISSUE THREAD

**Issue by rmagnum2002** [phuesler/payone_connect#3]
Hi @phuesler, need help with this error please, I have to integrate the payone system into a rails app and I find it very hard to do based on their poor documentation, and as if this is not enough I got this error also.. have I missed something?
Thank you.

```ruby
[1] pry(main)> payone = PayoneConnect.new('apikey', {mid: 12345, portalid: 3121, key: 'apikey', mode: 'test'})
=> #<PayoneConnect:0x0000000e685520
 @api_url=#<URI::Generic:0x0000000e685340 URL:apikey>,
 @request_data="mid=12345&portalid=3121&key=apikey&mode=test",
 @request_header={"Content-Type"=>"application/x-www-form-urlencoded"}>

[2] pry(main)> puts payone.request
URI::InvalidURIError: the scheme http does not accept registry part: :80 (or bad hostname?)
from /home/srosca/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/uri/generic.rb:214:in `initialize'
```

**Comment by rmagnum2002** [comment]
Base on your docs, first parameter in PayoneConnect.new should be `api_key` but it looks like it requires an url, when I changed it to server-api url I moved from the error above but got into another one that also might require your help, as you might know payone better.
Thank you.

```ruby
[15] pry(main)> payone = PayoneConnect.new('https://api.pay1.de/post-gateway/', {mid: 12345, portalid: 1234, key: 'api_key', mode: 'test', request: 'createaccess', aid: 45678, productid: 3254, clearingtype: 'cc'})

=> #<PayoneConnect:0x0000000e6bf748
 @api_url=#<URI::HTTPS:0x0000000e6bf540 URL:https://api.pay1.de/post-gateway/>,
 @request_data=
 "mid=12345&portalid=1234&key=api_key&mode=test&request=createaccess&aid=45678&productid=3254&clearingtype=cc",
 @request_header={"Content-Type"=>"application/x-www-form-urlencoded"}>

[16] pry(main)> puts payone.request
{:status=>"ERROR", :errorcode=>"2005", :errormessage=>"PortalID not found or no rights", :customermessage=>"An error occured while processing this transaction (wrong parameters)."}
```

**Comment by phuesler** [comment]
Hi,

I wasn't aware that people are still using this gem. The [code](https://github.com/phuesler/payone_connect/blob/68d35a1af6104a5ad3a16fedb2b6a5e02e14ce94/lib/payone_connect.rb#L9) that the documentation is in fact wrong, and that you have to pass in the endpoint. 

As for the error message, it looks like the payone API is missing a param. You can pass in any missing param, the [code](https://github.com/phuesler/payone_connect/blob/68d35a1af6104a5ad3a16fedb2b6a5e02e14ce94/lib/payone_connect.rb#L46) will happily pass it on the payone.

**Comment by rmagnum2002** [comment]
Well, Patrick, I got a few messages in a row related to missing params, like the one below:

```
{:status=>"ERROR", :errorcode=>"1721", :errormessage=>"Parameter {productid} faulty or missing", :customermessage=>"An error occured while processing this transaction (wrong parameters)."}
```

so I managed to add all of the missing params, ending with PortalID not found or no rights message.
payone explains this as this: 

```
2005   PortalID not found or no rights    Change PortalID
```

but I am sure I have the right portal id in params...
Anyway, if there is anything you can help with, please point me into a right direction, if not.. well, I'll just close this issue.
Thank you.

**Comment by phuesler** [comment]
I'm sorry, I cannot help you here. The code is passing on all the parameters to payone in the HTTP request. It is possible that there is a problem with your payone credentials or that they changed their API in the past 6 years. I wouldn't know, because I have no access to their documentation.

Good luck.
